### ISSUE TITLE
Calculation of PA

### ISSUE THREAD

**Issue by GPla** [saurf4ng/eTaPR#1]
The calculation of point-adjust (PA) is done differently than described in the [paper](https://dl.acm.org/doi/abs/10.1145/3178876.3185996).
It reads:

> if any point in an anomaly segment in the ground truth can be detected by a chosen threshold, we say this segment is detected correctly, and all points in this segment are treated as if they can be detected by this threshold.

However, this implementation only counts a segment as detected if more than `theta_r` % of the segment is detected.
This corresponds to the [PA%K protocol](https://arxiv.org/abs/2109.05257) proposed by Kim et al. 

An small example:

```python
import eTaPR_pkg as etapr
import numpy as np

y = np.ones(11)
y_hat = np.zeros(11)
y_hat[0] = 1

print(etapr.evaluate_w_streams(y, y_hat))
>>>  {..., 'point_adjust_precision': nan, 'point_adjust_recall': 0.0 }
```

With `theta_r = 0.0`, we get the expected result:

```python
print(etapr.evaluate_w_streams(y, y_hat, theta_r=0.0))
>>> {..., 'point_adjust_precision': 1.0, 'point_adjust_recall': 1.0}
```

**Comment by wshw4ng** [comment]
You're right.
I was confused about the threshold (I think the threshold is similar to theta_r). 
As soon as possible, I will update the correct PA.
Thanks for your comment.

**Comment by GPla** [comment]
Just a small follow up. A `theta_r=0.0` is incorrect and counts anomalies that have not been detected by any point. A very small value suffices.

```python
import eTaPR_pkg as etapr
import numpy as np

y = [0, 1, 1, 1, 0, 1, 1, 0]
y_hat = [0, 1, 0, 0, 0, 0, 0]

print(etapr.evaluate_w_streams(y, y_hat, theta_r=0.0))
>>> {..., 'point_adjust_precision': 1.0, 'point_adjust_recall': 1.0}

print(etapr.evaluate_w_streams(y, y_hat, theta_r=1e-8))
>>> {..., 'point_adjust_precision': 1.0, 'point_adjust_recall': 0.6}
```

**Comment by wshw4ng** [comment]
A theta_r is used for eTaPR, which is a new metric for time-series anomaly detection. I think that it seems to be correct (please see Eq.2 in the paper: [eTaPR](https://dl.acm.org/doi/abs/10.1145/3477314.3507024?casa_token=y37qw4upta0AAAAA:n9jv9GkkGb7c6RP-ySD-kMZsT1_o-JMjOjuDnIFU5EqYQd9l3WspSzPHKrtQOXU1HqM1SnJF6zgAjA)). If you want to use "point-adjust ones" in my package, it seems to be better to assign a small value for theta_r (as you already did).

**Comment by GPla** [comment]
I should've made my issue more clear, and I used these examples just to show the result of the calculation. The error is in [line 263/264](https://github.com/saurf4ng/eTaPR/blob/aff9d5533c98243c32227cb463840730778b48f2/eTaPR_pkg/etapr.py#L263) in `etapr.py`. The `theta_r` is used for the calculation of the point-adjust metrics and thus changes with it. Instead, PA should be independent of it (a small constant).

**Comment by wshw4ng** [comment]
I think my last update would be reflect your comment. 
I use a small value, 1e-10, for theta_r in the point-adjust metrics.
Could you check the lastest version?
